services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app_storage:/var/www/html/storage

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    network_mode: host
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90 --sleep=3
    env_file:
      - .env
    volumes:
      - app_storage:/var/www/html/storage

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    network_mode: host
    restart: unless-stopped
    command: php artisan schedule:work --verbose --no-interaction
    env_file:
      - .env
    volumes:
      - app_storage:/var/www/html/storage

volumes:
  app_storage: