<section class="mx-auto max-w-9xl px-4 py-6 sm:px-6 lg:px-8">

    {{-- header --}}
    <div class="flex flex-wrap items-start justify-between gap-4">
        <div>
            <div class="flex items-center gap-3">
                <a href="{{ route('hr.payroll.index') }}" class="text-sm text-slate-400 hover:text-slate-700">← Payroll</a>
            </div>
            <div class="mt-1 flex items-center gap-3">
                <h1 class="text-xl font-bold text-slate-900">{{ $batch->batch_number }}</h1>
                @if ($batch->batch_type !== 'regular')
                    @php
                        $typeClass = $batch->isPartial() ? 'bg-orange-100 text-orange-700' : 'bg-sky-100 text-sky-700';
                    @endphp
                    <span class="inline-flex items-center px-2 py-0.5 text-xs font-semibold {{ $typeClass }}">
                        {{ $batch->typeLabel() }}
                    </span>
                @endif
            </div>
            <p class="text-sm text-slate-500">
                {{ $batch->period_from->format('d M Y') }} – {{ $batch->period_to->format('d M Y') }}
                @if ($batch->payment_date)
                    · Payment: {{ $batch->payment_date->format('d M Y') }}
                @endif
                · Generated by {{ $batch->generatedBy?->name ?? '—' }}
            </p>
            @if ($batch->orgUnit)
                <span class="inline-flex items-center px-2 py-0.5 text-xs font-semibold bg-blue-100 text-slate-700">
                    {{ $batch->orgUnit->name }}
                </span>
            @endif
            @if ($batch->isArrear() && $batch->parentBatch)
                <p class="mt-1 text-xs text-sky-600">
                    Arrear of
                    <a href="{{ route('hr.payroll.batch.detail', $batch->parentBatch) }}" class="font-semibold underline">
                        {{ $batch->parentBatch->batch_number }}
                    </a>
                </p>
            @endif
        </div>

        @php
            $statusClass = match($batch->status) {
                'draft'     => 'bg-slate-100 text-slate-600',
                'returned'  => 'bg-red-100 text-red-700',
                'pending'   => 'bg-amber-100 text-amber-700',
                'approved'  => 'bg-green-100 text-green-700',
                'locked'    => 'bg-blue-100 text-blue-700',
                'disbursed' => 'bg-purple-100 text-purple-700',
                default     => 'bg-slate-100 text-slate-600',
            };
        @endphp

        <div class="flex flex-col items-end gap-2">
            {{-- status badges --}}
            <div class="flex items-center gap-2">
                <span class="inline-flex items-center px-3 py-1 text-sm font-semibold {{ $statusClass }}">
                    {{ $batch->statusLabel() }}
                </span>
                @if ($currentRoleLabel && $batch->status === 'pending')
                    <span class="inline-flex items-center bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-700">
                        With {{ $currentRoleLabel }}
                    </span>
                @endif
                @if ($batch->disbursed_at)
                    <span class="inline-flex items-center bg-purple-50 px-3 py-1 text-xs text-purple-600">
                        Disbursed {{ $batch->disbursed_at->format('d M Y') }}
                    </span>
                @endif
            </div>

            {{-- workflow decisions: destructive/back actions left, primary forward action right --}}
            @if ($canDiscardBatch || $canSubmitWorkflow || $canActOnWorkflow || $canMarkDisbursed)
                <div class="flex flex-wrap items-center justify-end gap-2">
                    @if ($canDiscardBatch)
                        <x-ui.button variant="danger" wire:click="openDiscardModal">Discard</x-ui.button>
                    @endif
                    @if ($canActOnWorkflow)
                        <x-ui.button variant="secondary" wire:click="openReturnModal">Return to HR</x-ui.button>
                    @endif
                    @if ($canSubmitWorkflow)
                        <x-ui.button variant="primary" wire:click="openSubmitModal">
                            {{ $batch->status === 'returned' ? 'Resubmit' : 'Submit' }}
                        </x-ui.button>
                    @endif
                    @if ($canActOnWorkflow)
                        <x-ui.button variant="primary" wire:click="openApproveModal">
                            {{ $currentRoleLabel === $finalApproverLabel ? 'Final Approve & Lock' : 'Approve & Forward' }}
                        </x-ui.button>
                    @endif
                    @if ($canMarkDisbursed)
                        <x-ui.button variant="primary" wire:click="openMarkDisbursedModal">Mark as Disbursed</x-ui.button>
                    @endif
                </div>
            @endif

            {{-- document utilities: uniform low-emphasis group, separated from decisions --}}
            @if ($canGenerateFinalDocuments || $canGeneratePayslips)
                <div class="flex flex-wrap items-center justify-end gap-2 border-t border-slate-100 pt-2">
                    @if ($canGeneratePayslips)
                        <x-ui.button variant="outline" wire:click="openGeneratePayslipsModal">Regenerate Payslips</x-ui.button>
                    @endif
                    @if ($canGenerateFinalDocuments)
                        <x-ui.button variant="outline" wire:click="openSanctionOrderModal">Generate Sanction Order</x-ui.button>
                        @foreach ($finalDocumentTypes as $type => $label)
                            <x-ui.button variant="outline" wire:click="downloadFinalPayrollDocument('{{ $type }}')">Generate {{ $label }}</x-ui.button>
                        @endforeach
                        <x-ui.button variant="outline" wire:click="openUploadBatchDocumentModal">Upload Document</x-ui.button>
                    @endif
                </div>
            @endif
        </div>
    </div>

    @if (session('status'))
        <x-ui.alert variant="success" class="mt-5">{{ session('status') }}</x-ui.alert>
    @endif

    @if ($canEditPayroll && ! $canSubmitWorkflow && in_array($batch->status, ['draft', 'returned'], true))
        <div class="mt-5 border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            You can edit payroll adjustments for this batch, but only Head Office HR can submit or resubmit it to the approval workflow.
        </div>
    @endif

    {{-- partial batch notice --}}
    @if ($batch->isPartial())
        <div class="mt-5 border border-orange-200 bg-orange-50 px-4 py-3 text-sm text-orange-800">
            <strong>Partial Batch</strong> — The default disbursement is <strong>{{ $batch->default_disbursement_pct }}%</strong>
            of each employee's net salary. The remaining outstanding amount will be released as an arrear batch.
            Individual employees can have their disbursement % overridden via the Adjust page.
        </div>
    @endif

    @if ($batch->isPartial() && $batch->status === 'disbursed' && !$batch->hasArrear())
        <div class="mt-3 border border-sky-300 bg-sky-50 px-4 py-3 text-sm text-sky-800">
            <strong>Arrear Pending</strong> — This batch has been disbursed but the outstanding arrear batch has not been generated yet.
            Go back to the
            <a href="{{ route('hr.payroll.index') }}" class="font-semibold underline">Payroll index</a>
            and click <strong>Generate Arrear</strong> to release the outstanding amounts.
        </div>
    @endif

    @if ($batch->isPartial() && $batch->hasArrear())
        <div class="mt-3 border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">
            Arrear batch has been generated for this partial batch.
        </div>
    @endif

    {{-- summary cards --}}
    @php $cardCols = $batch->isPartial() ? 'xl:grid-cols-6' : 'xl:grid-cols-5'; @endphp
    <div class="mt-5 grid gap-4 sm:grid-cols-2 {{ $cardCols }}">
        <x-ui.stat-card label="Employees"      :value="number_format($summary['employees'])" hint="In this batch" />
        <x-ui.stat-card label="Gross Total"    :value="'₹' . number_format($summary['gross'], 2)"      variant="info" />
        <x-ui.stat-card label="Deductions"     :value="'₹' . number_format($summary['deductions'], 2)" variant="danger" />
        <x-ui.stat-card label="Net Payable"    :value="'₹' . number_format($summary['net'], 2)"        variant="success" />

        @if ($batch->isPartial())
            <x-ui.stat-card
                label="To Be Disbursed"
                :value="'₹' . number_format($summary['disbursed'], 2)"
                hint="Across all employees"
                variant="warning"
            />
            <x-ui.stat-card
                label="Outstanding"
                :value="'₹' . number_format($summary['net'] - $summary['disbursed'], 2)"
                hint="To be paid as arrear"
                variant="danger"
            />
        @endif

        <x-ui.stat-card
            label="Pending Leave Review"
            :value="number_format($summary['pending_review'])"
            hint="Employees needing HR review"
            variant="{{ $summary['pending_review'] > 0 ? 'warning' : 'success' }}"
        />
        <x-ui.stat-card
            label="Payslips"
            :value="number_format($summary['payslips'])"
            hint="Issued for employees"
            variant="{{ $summary['payslips'] > 0 ? 'info' : 'default' }}"
        />
    </div>

    @if ($summary['pending_review'] > 0)
        <div class="mt-4 border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            <strong>{{ $summary['pending_review'] }} employee(s)</strong> have leave adjustments that haven't been reviewed by HR.
            Net salary figures may change after review. Approve the batch only after all leave reviews are complete.
        </div>
    @endif

    {{-- workflow and change history --}}
    <div class="mt-5 grid gap-4 lg:grid-cols-2">
        <x-ui.card title="Approval History" description="Forwarding and return actions recorded for this batch.">
            @if ($workflowActions->isEmpty())
                <p class="py-6 text-center text-sm text-slate-400">No workflow action has been recorded yet.</p>
            @else
                <div class="space-y-3">
                    @foreach ($workflowActions as $action)
                        @php
                            $actionLabel = match($action->action) {
                                'submitted' => 'Submitted',
                                'resubmitted' => 'Resubmitted',
                                'approved' => 'Approved',
                                'final_approved' => 'Final Approved',
                                'returned' => 'Returned',
                                default => str($action->action)->replace('_', ' ')->title()->toString(),
                            };
                            $actionClass = match($action->action) {
                                'returned' => 'bg-red-50 text-red-700',
                                'final_approved' => 'bg-blue-50 text-blue-700',
                                default => 'bg-green-50 text-green-700',
                            };
                        @endphp
                        <div class="border border-slate-100 bg-slate-50 px-3 py-2">
                            <div class="flex flex-wrap items-center justify-between gap-2">
                                <div>
                                    <span class="inline-flex items-center px-2 py-0.5 text-xs font-semibold {{ $actionClass }}">
                                        {{ $actionLabel }}
                                    </span>
                                    <span class="ml-2 text-sm font-medium text-slate-800">
                                        {{ $action->workflowStep?->name ?? 'Workflow' }}
                                    </span>
                                </div>
                                <span class="text-xs text-slate-400">
                                    {{ $action->acted_at?->format('d M Y, h:i A') ?? $action->created_at->format('d M Y, h:i A') }}
                                </span>
                            </div>
                            <p class="mt-1 text-xs text-slate-500">
                                By {{ $action->actedBy?->name ?? 'System' }}
                                @if ($action->remarks)
                                    · {{ $action->remarks }}
                                @endif
                            </p>
                        </div>
                    @endforeach
                </div>
            @endif
        </x-ui.card>

        <x-ui.card title="Payroll Change Log" description="Adjustment, leave review, and disbursement edits visible to every approver.">
            @if ($adjustmentLogs->isEmpty())
                <p class="py-6 text-center text-sm text-slate-400">No payroll edits have been logged yet.</p>
            @else
                <div class="space-y-3">
                    @foreach ($adjustmentLogs as $log)
                        @php
                            $employee = $log->payrollItem?->employee;
                            $actorRole = \App\Models\Role::labelFor($log->role);
                            $logLabel = match($log->action) {
                                'adjustment_created' => 'Adjustment Added',
                                'adjustment_updated' => 'Adjustment Updated',
                                'adjustment_deleted' => 'Adjustment Removed',
                                'disbursement_updated' => 'Disbursement Updated',
                                'disbursement_reset' => 'Disbursement Reset',
                                'leave_review_saved' => 'Leave Review Saved',
                                'leave_review_reset' => 'Leave Review Reset',
                                default => str($log->action)->replace('_', ' ')->title()->toString(),
                            };
                            $netDelta = (float) ($log->new_item_net_salary ?? 0) - (float) ($log->old_item_net_salary ?? 0);
                        @endphp
                        <div class="border border-slate-100 bg-slate-50 px-3 py-2">
                            <div class="flex flex-wrap items-center justify-between gap-2">
                                <div>
                                    <span class="text-sm font-semibold text-slate-900">{{ $logLabel }}</span>
                                    <span class="ml-2 text-xs text-slate-500">
                                        {{ $employee?->full_name ?? 'Employee' }}
                                        @if ($employee?->employee_code)
                                            · {{ $employee->employee_code }}
                                        @endif
                                    </span>
                                </div>
                                <span class="text-xs text-slate-400">{{ $log->created_at->format('d M Y, h:i A') }}</span>
                            </div>
                            <div class="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500">
                                <span>{{ $log->actor?->name ?? 'System' }}</span>
                                <span>· {{ $actorRole }}</span>
                                @if ($log->workflowStep)
                                    <span>· {{ $log->workflowStep->name }}</span>
                                @endif
                                @if ($log->old_item_net_salary !== null && $log->new_item_net_salary !== null)
                                    <span class="{{ $netDelta < 0 ? 'text-red-600' : ($netDelta > 0 ? 'text-green-700' : 'text-slate-500') }}">
                                        · Net {{ $netDelta >= 0 ? '+' : '' }}₹{{ number_format($netDelta, 2) }}
                                    </span>
                                @endif
                            </div>
                            @if ($log->remarks)
                                <p class="mt-1 text-xs text-slate-600">{{ $log->remarks }}</p>
                            @endif
                        </div>
                    @endforeach
                </div>
            @endif
        </x-ui.card>
    </div>

    {{-- batch documents --}}
    <x-ui.card class="mt-5" title="Batch Documents" description="Generated payroll letters, salary statements, and uploaded signed copies for this batch.">
        @if ($batchDocuments->isEmpty())
            <p class="py-6 text-center text-sm text-slate-400">No batch documents attached yet.</p>
        @else
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-slate-200 text-sm">
                    <thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
                        <tr>
                            <th class="px-3 py-2">Document</th>
                            <th class="px-3 py-2">Status</th>
                            <th class="px-3 py-2">Uploaded By</th>
                            <th class="px-3 py-2">Date</th>
                            <th class="px-3 py-2 text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100">
                        @foreach ($batchDocuments as $document)
                            <tr>
                                <td class="px-3 py-2">
                                    <span class="font-medium text-slate-900">{{ $document->title }}</span>
                                    <p class="text-xs text-slate-400">{{ $document->file_name }}</p>
                                    @if ($document->remarks)
                                        <p class="mt-1 text-xs text-slate-500">{{ $document->remarks }}</p>
                                    @endif
                                </td>
                                <td class="px-3 py-2">
                                    <span class="inline-flex items-center bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-700">
                                        {{ str($document->status)->replace('_', ' ')->title() }}
                                    </span>
                                    <p class="text-xs text-slate-400">v{{ $document->version }}</p>
                                </td>
                                <td class="px-3 py-2 text-slate-600">{{ $document->uploadedBy?->name ?? 'System' }}</td>
                                <td class="px-3 py-2 text-slate-500">{{ $document->created_at->format('d M Y, h:i A') }}</td>
                                <td class="px-3 py-2 text-right">
                                    @if ($document->status !== 'generated' || $canGenerateFinalDocuments)
                                        <button
                                            type="button"
                                            wire:click="downloadBatchDocument({{ $document->id }})"
                                            class="text-sm font-medium text-blue-700 hover:underline"
                                        >
                                            Download
                                        </button>
                                    @else
                                        <span class="text-xs text-slate-400">HO only</span>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </x-ui.card>

    {{-- filters --}}
    <x-ui.card class="mt-5">
        <div class="grid gap-3 sm:grid-cols-2">
            <x-ui.input
                wire:model.live.debounce.300ms="search"
                label="Search Employee"
                placeholder="Name or employee code"
            />
            <x-ui.select
                wire:model.live="filterStatus"
                label="Status"
                :options="['draft' => 'Draft', 'pending' => 'Pending', 'adjusted' => 'Adjusted', 'approved' => 'Approved']"
                placeholder="All"
            />
        </div>
    </x-ui.card>

    {{-- employee table --}}
    @php
        $headers = ['Employee', 'Basic', 'Gross', 'Deductions', 'LWP Days', 'Net Payable'];
        if ($batch->isPartial()) {
            $headers[] = 'To Disburse';
            $headers[] = 'Outstanding';
        }
        $headers[] = 'Leave Review';
        $headers[] = 'Payslip';
        $headers[] = '';
    @endphp

    <div class="mt-5">
        <x-ui.table :headers="$headers">
            @forelse ($items as $item)
                <tr class="transition hover:bg-slate-50 {{ $item->pending_review_count > 0 ? 'bg-amber-50/40' : '' }}">
                    <x-ui.table.td>
                        <span class="font-medium text-slate-900">{{ $item->employee?->full_name ?? '—' }}</span>
                        <p class="text-xs text-slate-400">{{ $item->employee?->employee_code ?? '' }}</p>
                        <p class="text-xs text-slate-400">{{ $item->employee?->orgUnit?->name ?? '' }}</p>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-700">₹{{ number_format($item->basic_salary, 2) }}</span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-700">₹{{ number_format($item->gross_salary, 2) }}</span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        {{-- system deductions --}}
                        <span class="text-sm {{ $item->total_deductions > 0 ? 'text-red-600' : 'text-slate-400' }}">
                            ₹{{ number_format($item->total_deductions, 2) }}
                        </span>
                        {{-- manual adjustment lines --}}
                        @foreach ($item->adjustments as $adj)
                            <p class="mt-0.5 text-xs {{ $adj->type === 'deduction' ? 'text-red-500' : 'text-green-600' }}">
                                {{ $adj->type === 'deduction' ? '−' : '+' }}₹{{ number_format($adj->amount, 2) }}
                                <span class="text-slate-400">· {{ $adj->label }}</span>
                            </p>
                        @endforeach
                    </x-ui.table.td>
                    <x-ui.table.td>
                        @if ($item->leave_without_pay_days > 0)
                            <span class="text-sm font-medium text-red-600">{{ $item->leave_without_pay_days }}</span>
                        @else
                            <span class="text-sm text-slate-400">—</span>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm font-semibold text-slate-900">₹{{ number_format($item->net_salary, 2) }}</span>
                    </x-ui.table.td>

                    @if ($batch->isPartial())
                        <x-ui.table.td>
                            <span class="text-sm font-semibold text-orange-700">
                                ₹{{ number_format($item->disbursed_amount, 2) }}
                            </span>
                            @if ($item->hasCustomDisbursementPct())
                                <p class="text-xs font-medium text-orange-500">{{ $item->disbursement_pct }}% (custom)</p>
                            @else
                                <p class="text-xs text-slate-400">{{ $item->disbursement_pct }}%</p>
                            @endif
                        </x-ui.table.td>
                        <x-ui.table.td>
                            <span class="text-sm text-slate-500">₹{{ number_format($item->outstanding_amount, 2) }}</span>
                        </x-ui.table.td>
                    @endif

                    <x-ui.table.td>
                        @if ($item->leave_adjustments_count > 0)
                            @if ($item->pending_review_count > 0)
                                <span class="inline-flex items-center bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-700">
                                    {{ $item->pending_review_count }} pending
                                </span>
                            @else
                                <span class="inline-flex items-center bg-green-100 px-2 py-0.5 text-xs font-semibold text-green-700">
                                    Reviewed
                                </span>
                            @endif
                        @else
                            <span class="text-xs text-slate-400">No leave</span>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        @if ($item->payslip?->status === 'issued')
                            <span class="inline-flex items-center bg-green-100 px-2 py-0.5 text-xs font-semibold text-green-700">
                                Issued
                            </span>
                            <p class="text-xs text-slate-400">{{ $item->payslip->generated_at?->format('d M Y') }}</p>
                            <a
                                href="{{ route('hr.payroll.payslip.print', $item->payslip) }}"
                                target="_blank"
                                rel="noopener"
                                class="mt-0.5 inline-block text-xs font-medium text-blue-700 hover:underline"
                            >
                                View / Print
                            </a>
                        @else
                            <span class="text-xs text-slate-400">Not generated</span>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <div class="flex flex-col gap-1">
                            @if ($item->leave_adjustments_count > 0 && $canEditPayroll)
                                <a
                                    href="{{ route('hr.payroll.leave.review', [$batch, $item]) }}"
                                    class="text-sm font-medium text-blue-700 hover:underline"
                                >
                                    Review Leave
                                </a>
                            @endif
                            @if ($canEditPayroll)
                                <a
                                    href="{{ route('hr.payroll.item.adjustments', [$batch, $item]) }}"
                                    class="text-sm font-medium text-slate-600 hover:underline"
                                >
                                    {{ $item->adjustments_count > 0 ? 'Edit Adjustments (' . $item->adjustments_count . ')' : 'Adjust' }}
                                </a>
                            @endif
                        </div>
                    </x-ui.table.td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}" class="px-4 py-10 text-center text-sm text-slate-400">
                        No employees found in this batch.
                    </td>
                </tr>
            @endforelse
        </x-ui.table>

        <div class="mt-4">{{ $items->links() }}</div>
    </div>

    {{-- submit workflow modal --}}
    <x-ui.modal name="submit-payroll-batch" title="{{ $batch->status === 'returned' ? 'Resubmit Payroll' : 'Submit Payroll' }}">
        <div class="space-y-4">
            <p class="text-sm text-slate-600">
                Send <strong>{{ $batch->batch_number }}</strong> to <strong>SPO FM</strong> for payroll approval.
                @if ($summary['pending_review'] > 0)
                    <span class="mt-2 block text-amber-700">
                        Warning: {{ $summary['pending_review'] }} employee(s) still have unreviewed leave adjustments.
                    </span>
                @endif
            </p>
            <x-ui.textarea
                wire:model="workflowRemarks"
                label="Remarks"
                placeholder="Optional submission note"
                :error="$errors->first('workflowRemarks')"
            />
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'submit-payroll-batch' })">Cancel</x-ui.button>
            <x-ui.button wire:click="submitBatch">Submit</x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- approve workflow modal --}}
    <x-ui.modal name="approve-payroll-batch" title="{{ $currentRoleLabel === $finalApproverLabel ? 'Final Approve & Lock' : 'Approve & Forward' }}">
        <div class="space-y-4">
            <p class="text-sm text-slate-600">
                Approve <strong>{{ $batch->batch_number }}</strong>
                as <strong>{{ $currentRoleLabel ?? 'current approver' }}</strong>.
                @if ($currentRoleLabel === $finalApproverLabel)
                    This is the final approval and will lock the batch.
                @else
                    The batch will move to the next approver.
                @endif
            </p>
            @if ($summary['pending_review'] > 0)
                <p class="text-sm text-amber-700">
                    Warning: {{ $summary['pending_review'] }} employee(s) still have unreviewed leave adjustments.
                </p>
            @endif
            <x-ui.textarea
                wire:model="workflowRemarks"
                label="Remarks"
                placeholder="Optional approval note"
                :error="$errors->first('workflowRemarks')"
            />
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'approve-payroll-batch' })">Cancel</x-ui.button>
            <x-ui.button wire:click="approveCurrentStep">
                {{ $currentRoleLabel === $finalApproverLabel ? 'Final Approve & Lock' : 'Approve & Forward' }}
            </x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- return workflow modal --}}
    <x-ui.modal name="return-payroll-batch" title="Return to HR">
        <div class="space-y-4">
            <p class="text-sm text-slate-600">
                Return <strong>{{ $batch->batch_number }}</strong> to HR for correction. A reason is required and will be visible in the approval history.
            </p>
            <x-ui.textarea
                wire:model="workflowRemarks"
                label="Return Reason"
                placeholder="What should HR review or correct?"
                required
                :error="$errors->first('workflowRemarks')"
            />
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'return-payroll-batch' })">Cancel</x-ui.button>
            <x-ui.button variant="danger" wire:click="returnBatchToHr">Return to HR</x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- regenerate payslips modal --}}
    <x-ui.modal name="generate-payslips" title="Regenerate Payslips">
        <p class="text-sm text-slate-600">
            Regenerate payslip documents for all employees in <strong>{{ $batch->batch_number }}</strong>.
            Any existing payslips will be refreshed with a new version.
        </p>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'generate-payslips' })">Cancel</x-ui.button>
            <x-ui.button wire:click="generatePayslips" wire:loading.attr="disabled">
                <span wire:loading.remove wire:target="generatePayslips">Regenerate Payslips</span>
                <span wire:loading wire:target="generatePayslips">Regenerating...</span>
            </x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- generate sanction order modal --}}
    <x-ui.modal name="generate-sanction-order" title="Generate Sanction Order">
        <div class="space-y-4">
            <p class="text-sm text-slate-600">
                Generate the editable Word sanction order for <strong>{{ $batch->batch_number }}</strong>.
                Figures are taken from this batch automatically.
            </p>

            <x-ui.select
                wire:model="sanctionActivityId"
                label="Activity"
                :options="$sanctionActivities"
                placeholder="Select activity"
                :error="$errors->first('sanctionActivityId')"
            />

            <x-ui.select
                wire:model="sanctionSignatory"
                label="Signatory"
                :options="$sanctionSignatories"
                :error="$errors->first('sanctionSignatory')"
            />

            <div class="grid gap-4 sm:grid-cols-2">
                <x-ui.input
                    wire:model="sanctionReferenceSerial"
                    label="Reference Serial"
                    hint="Appended after the No. prefix. Leave blank to fill by hand."
                    :error="$errors->first('sanctionReferenceSerial')"
                />
                <x-ui.input
                    wire:model="sanctionReferenceDate"
                    label="Reference Date"
                    placeholder="e.g. 25.06.2026"
                    hint="Leave blank to fill by hand."
                    :error="$errors->first('sanctionReferenceDate')"
                />
            </div>

            <div class="grid gap-4 sm:grid-cols-2">
                <x-ui.input
                    wire:model="sanctionMemoSerial"
                    label="Memo Serial"
                    hint="Appended after the Memo No. prefix."
                    :error="$errors->first('sanctionMemoSerial')"
                />
                <x-ui.input
                    wire:model="sanctionMemoDate"
                    label="Memo Date"
                    placeholder="e.g. 25.06.2026"
                    :error="$errors->first('sanctionMemoDate')"
                />
            </div>

            <x-ui.textarea
                wire:model="sanctionCopyTo"
                label="Copy To"
                rows="4"
                hint="One recipient per line. Edit as needed for this letter."
                :error="$errors->first('sanctionCopyTo')"
            />
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'generate-sanction-order' })">Cancel</x-ui.button>
            <x-ui.button wire:click="generateSanctionOrder" wire:loading.attr="disabled">
                <span wire:loading.remove wire:target="generateSanctionOrder">Generate &amp; Download</span>
                <span wire:loading wire:target="generateSanctionOrder">Generating...</span>
            </x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- upload batch document modal --}}
    <x-ui.modal name="upload-batch-document" title="Upload Batch Document">
        <div class="space-y-4">
            <p class="text-sm text-slate-600">
                Attach the signed, printed, or supporting copy for <strong>{{ $batch->batch_number }}</strong>. It will also appear in the HR Documents module.
            </p>
            <x-ui.input
                wire:model="batchDocumentTitle"
                label="Document Title"
                placeholder="Signed sanction letter or salary statement"
                required
                :error="$errors->first('batchDocumentTitle')"
            />
            <x-ui.textarea
                wire:model="batchDocumentRemarks"
                label="Remarks"
                placeholder="Optional note"
                :error="$errors->first('batchDocumentRemarks')"
            />
            <div>
                <label class="block text-sm font-medium text-slate-700">File</label>
                <input
                    type="file"
                    wire:model="batchDocumentFile"
                    class="mt-1 block w-full text-sm text-slate-600 file:mr-3 file:border-0 file:bg-slate-100 file:px-3 file:py-2 file:text-sm file:font-medium file:text-slate-700"
                >
                @error('batchDocumentFile')
                    <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                @enderror
            </div>
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'upload-batch-document' })">Cancel</x-ui.button>
            <x-ui.button wire:click="uploadBatchDocument" wire:loading.attr="disabled">
                <span wire:loading.remove wire:target="uploadBatchDocument">Upload</span>
                <span wire:loading wire:target="uploadBatchDocument">Uploading...</span>
            </x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- mark disbursed modal --}}
    <x-ui.modal name="mark-disbursed" title="Mark as Disbursed">
        <div class="space-y-3">
            <p class="text-sm text-slate-600">
                Confirm that salary for <strong>{{ $batch->batch_number }}</strong> has been credited to employees.
                @if ($batch->payment_date)
                    <br>Scheduled payment date: <strong>{{ $batch->payment_date->format('d M Y') }}</strong>.
                @endif
            </p>
            <p class="text-sm text-slate-500">
                Payslips will be generated automatically for all employees in this batch.
            </p>
        </div>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'mark-disbursed' })">Cancel</x-ui.button>
            <x-ui.button wire:click="markAsDisbursed">Confirm Disbursed</x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

    {{-- confirm discard modal --}}
    <x-ui.modal name="discard-payroll-batch" title="Discard Batch">
        <p class="text-sm text-slate-600">
            This will permanently delete <strong>{{ $batch->batch_number }}</strong> and all its employee records.
            This cannot be undone.
        </p>
        <x-slot:footer>
            <x-ui.button variant="secondary" x-on:click="$dispatch('close-modal', { name: 'discard-payroll-batch' })">Cancel</x-ui.button>
            <x-ui.button variant="danger" wire:click="discardBatch">Yes, Discard</x-ui.button>
        </x-slot:footer>
    </x-ui.modal>

</section>
