<section class="mx-auto max-w-9xl px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-start justify-between gap-4">
        <x-ui.page-header
            title="Payroll"
            description="Generate, review, and approve monthly payroll batches."
        />

        @if ($canGeneratePayroll)
            <x-ui.button wire:click="openGenerateModal">
                Generate New Batch
            </x-ui.button>
        @endif
    </div>

    @if (session('status'))
        <x-ui.alert variant="success" class="mt-5">{{ session('status') }}</x-ui.alert>
    @endif

    @if (session('error'))
        <x-ui.alert variant="danger" class="mt-5">{{ session('error') }}</x-ui.alert>
    @endif

    {{-- summary cards --}}
    <div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
        <x-ui.stat-card label="Total Batches"  :value="$summary['total']"     hint="All time" />
        <x-ui.stat-card label="Draft"          :value="$summary['draft']"     hint="Not yet submitted" />
        <x-ui.stat-card label="Returned"       :value="$summary['returned']"  hint="Needs HR correction" variant="danger" />
        <x-ui.stat-card label="Pending"        :value="$summary['pending']"   hint="Awaiting approval" variant="warning" />
        <x-ui.stat-card label="Locked"         :value="$summary['locked']"    hint="MD approved" variant="success" />
        <x-ui.stat-card label="Disbursed"      :value="$summary['disbursed']" hint="Salary credited"    variant="info" />
    </div>

    {{-- filters --}}
    <x-ui.card class="mt-5">
        <div class="grid gap-3 sm:grid-cols-2 md:grid-cols-3">
            <x-ui.input
                wire:model.live="filterMonth"
                type="month"
                label="Month"
            />
            <x-ui.select
                wire:model.live="filterStatus"
                label="Status"
                :options="$statusOptions"
                placeholder="All statuses"
            />
        </div>
    </x-ui.card>

    {{-- batch list --}}
    <div class="mt-5">
        <x-ui.table :headers="['Batch', 'Period', 'Employees', 'Gross', 'Net Payable', 'Disbursed', 'Status', 'Generated By', '']">
            @forelse ($batches as $batch)
                @php
                    $statusMap = [
                        'draft'     => 'bg-slate-100 text-slate-600',
                        'returned'  => 'bg-red-100 text-red-700',
                        'pending'   => 'bg-amber-100 text-amber-700',
                        'approved'  => 'bg-green-100 text-green-700',
                        'locked'    => 'bg-blue-100 text-blue-700',
                        'disbursed' => 'bg-purple-100 text-purple-700',
                    ];

                    $typeMap = [
                        'partial' => 'bg-orange-100 text-orange-700',
                        'arrear'  => 'bg-sky-100 text-sky-700',
                    ];

                    $statusClass = $statusMap[$batch->status]     ?? 'bg-slate-100 text-slate-600';
                    $typeClass   = $typeMap[$batch->batch_type]   ?? '';
                @endphp
                <tr class="transition hover:bg-slate-50">
                    <x-ui.table.td>
                        <div class="flex items-center gap-2">
                            <span class="font-mono text-sm font-semibold text-slate-900">{{ $batch->batch_number }}</span>
                            @if ($batch->batch_type !== 'regular')
                                <span class="inline-flex items-center px-1.5 py-0.5 text-xs font-semibold {{ $typeClass }}">
                                    {{ $batch->typeLabel() }}
                                </span>
                            @endif
                        </div>
                        @if ($batch->orgUnit)
                            <p class="text-xs text-slate-400">{{ $batch->orgUnit->name }}</p>
                        @endif
                        @if ($batch->isPartial())
                            <p class="text-xs text-orange-600">{{ $batch->default_disbursement_pct }}% disbursement</p>
                        @endif
                        @if ($batch->isArrear() && $batch->parentBatch)
                            <p class="text-xs text-sky-600">Arrear of {{ $batch->parentBatch->batch_number }}</p>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-700">
                            {{ $batch->period_from->format('d M Y') }} - {{ $batch->period_to->format('d M Y') }}
                        </span>
                        @if ($batch->payment_date)
                            <p class="text-xs text-slate-400">Payment: {{ $batch->payment_date->format('d M Y') }}</p>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-700">{{ number_format($batch->items_count) }}</span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-700">₹{{ number_format($batch->gross_total, 2) }}</span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm font-medium text-slate-900">₹{{ number_format($batch->net_total, 2) }}</span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        @if ($batch->isPartial() && $batch->status === 'disbursed')
                            <span class="text-sm font-medium text-orange-700">₹{{ number_format($batch->disbursed_total, 2) }}</span>
                            <p class="text-xs text-slate-400">Outstanding: ₹{{ number_format($batch->net_total - $batch->disbursed_total, 2) }}</p>
                        @elseif ($batch->isPartial())
                            <span class="text-xs text-orange-600">{{ $batch->default_disbursement_pct }}% when disbursed</span>
                        @else
                            <span class="text-sm text-slate-500">—</span>
                        @endif
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="inline-flex items-center px-2 py-0.5 text-xs font-semibold {{ $statusClass }}">
                            {{ $batch->statusLabel() }}
                        </span>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <span class="text-sm text-slate-600">{{ $batch->generatedBy?->name ?? '—' }}</span>
                        <p class="text-xs text-slate-400">{{ $batch->created_at->format('d M Y') }}</p>
                    </x-ui.table.td>
                    <x-ui.table.td>
                        <div class="flex flex-col gap-1">
                            <a
                                href="{{ route('hr.payroll.batch.detail', $batch) }}"
                                class="text-sm font-medium text-blue-700 hover:underline"
                            >
                                View
                            </a>
                            @if ($batch->isPartial() && $batch->status === 'disbursed' && !$batch->hasArrear())
                                <button
                                    wire:click="generateArrear({{ $batch->id }})"
                                    wire:confirm="Generate arrear batch for {{ $batch->batch_number }}? This will create a new batch for all outstanding amounts."
                                    class="text-left text-sm font-medium text-sky-700 hover:underline"
                                >
                                    Generate Arrear
                                </button>
                            @endif
                            @if ($batch->isPartial() && $batch->hasArrear())
                                <span class="text-xs text-slate-400">Arrear generated</span>
                            @endif
                        </div>
                    </x-ui.table.td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" class="px-4 py-10 text-center text-sm text-slate-400">
                        No payroll batches found. Generate your first batch to get started.
                    </td>
                </tr>
            @endforelse
        </x-ui.table>

        <div class="mt-4">
            {{ $batches->links() }}
        </div>
    </div>

    {{-- generate modal --}}
    <x-ui.modal name="generate-payroll" title="Generate New Payroll Batch">
        <div class="space-y-4">
            @error('generate')
                <x-ui.alert variant="danger">{{ $message }}</x-ui.alert>
            @enderror

            <div class="grid gap-4 sm:grid-cols-2">
                <x-ui.input
                    wire:model="periodFrom"
                    type="date"
                    label="Period From"
                    hint="Usually 25th of last month"
                />
                <x-ui.input
                    wire:model="periodTo"
                    type="date"
                    label="Period To"
                    hint="Usually 25th of this month"
                />
            </div>

            <x-ui.input
                wire:model="paymentDate"
                type="date"
                label="Payment Date"
                hint="Date salary will be credited"
            />

            @if ($isHeadOfficeHr)
                <div x-data="{ q: '' }">
                    <div class="mb-1.5 flex items-center justify-between">
                        <p class="text-sm font-medium text-slate-700">
                            Offices
                            @if (count($orgUnitIds))
                                <span class="font-normal text-slate-400">({{ count($orgUnitIds) }} selected)</span>
                            @endif
                        </p>
                        <div class="flex items-center gap-3 text-xs">
                            <button type="button" wire:click="selectAllOffices" class="font-medium text-blue-700 hover:underline">Select all</button>
                            @if (count($orgUnitIds))
                                <button type="button" wire:click="clearOffices" class="font-medium text-slate-500 hover:underline">Clear</button>
                            @endif
                        </div>
                    </div>

                    <input
                        type="text"
                        x-model="q"
                        placeholder="Search offices…"
                        class="mb-2 block w-full border border-slate-300 px-3 py-1.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100"
                    >

                    <div class="space-y-2 rounded border border-slate-200 bg-slate-50 px-3 py-2.5" style="max-height: 14rem; overflow-y: auto;">
                        @foreach ($orgUnits as $id => $name)
                            <label
                                wire:key="office-{{ $id }}"
                                class="flex cursor-pointer items-center gap-2.5"
                                x-show="q === '' || @js(strtolower($name)).includes(q.toLowerCase().trim())"
                            >
                                <input
                                    type="checkbox"
                                    wire:model.live="orgUnitIds"
                                    value="{{ $id }}"
                                    class="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                                >
                                <span class="text-sm text-slate-700">{{ $name }}</span>
                            </label>
                        @endforeach
                    </div>
                    <p class="mt-1 text-xs text-slate-400">Select at least one office. Your selection is saved for next time.</p>
                    @error('orgUnitIds')
                        <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                    @error('orgUnitIds.*')
                        <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>
            @else
                <x-ui.select
                    wire:model.live="orgUnitId"
                    label="Organisation Unit"
                    :options="$orgUnits"
                    placeholder="Select organisation unit"
                    :error="$errors->first('orgUnitId')"
                />
            @endif

            <div>
                <p class="mb-1.5 text-sm font-medium text-slate-700">Department Streams</p>
                <div class="space-y-2 rounded border border-slate-200 bg-slate-50 px-3 py-2.5">
                    @foreach ($departmentStreams as $id => $name)
                        <label class="flex cursor-pointer items-center gap-2.5">
                            <input
                                type="checkbox"
                                wire:model="departmentStreamIds"
                                value="{{ $id }}"
                                class="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                            >
                            <span class="text-sm text-slate-700">{{ $name }}</span>
                        </label>
                    @endforeach
                </div>
                <p class="mt-1 text-xs text-slate-400">Leave all unchecked to include every stream available for the selected office(s).</p>
                @error('departmentStreamIds')
                    <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                @enderror
                @error('departmentStreamIds.*')
                    <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                @enderror
            </div>

            {{-- batch type --}}
            <x-ui.select
                wire:model.live="batchType"
                label="Batch Type"
                :options="['regular' => 'Regular', 'partial' => 'Partial (Budget Constraint)']"
            />

            {{-- disbursement % — only shown for partial --}}
            @if ($batchType === 'partial')
                <div>
                    <x-ui.input
                        wire:model="disbursementPct"
                        type="number"
                        min="1"
                        max="99"
                        step="0.01"
                        label="Disbursement Percentage"
                        hint="Percentage of net salary to disburse now. Remaining will be paid as arrear."
                    />
                    @error('disbursementPct')
                        <p class="mt-1 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                <div class="border border-orange-200 bg-orange-50 px-4 py-3 text-sm text-orange-800">
                    A <strong>Partial</strong> batch disburses only the set percentage of each employee's net salary.
                    The remaining amount must be released later as an <strong>Arrear</strong> batch.
                </div>
            @else
                <div class="border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                    This will generate a <strong>draft</strong> batch. No salaries are finalised until the batch is approved and locked.
                </div>
            @endif
        </div>

        <x-slot:footer>
            <x-ui.button variant="secondary" wire:click="closeGenerateModal">Cancel</x-ui.button>
            <x-ui.button wire:click="generate" wire:loading.attr="disabled">
                <span wire:loading.remove wire:target="generate">Generate Batch</span>
                <span wire:loading wire:target="generate">Generating…</span>
            </x-ui.button>
        </x-slot:footer>
    </x-ui.modal>
</section>
