<?php

namespace App\Services\Payroll;

use App\Models\Document;
use App\Models\PayrollBatch;
use App\Models\User;
use App\Services\Documents\SimplePdfService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PayrollBatchDocumentService
{
    public const SANCTION_LETTER = 'sanction_letter';
    public const PAY_ISSUANCE_LETTER = 'pay_issuance_letter';

    public const TYPES = [
        self::SANCTION_LETTER => 'Sanction Letter',
        self::PAY_ISSUANCE_LETTER => 'Pay Issuance Letter',
    ];

    public function __construct(
        private readonly PayrollWorkflowService $workflow,
        private readonly SimplePdfService $pdf,
    ) {}

    public function generate(PayrollBatch $batch, string $type, ?User $user = null): Document
    {
        $user ??= Auth::user();

        abort_unless($this->workflow->canGenerateFinalPayrollDocuments($batch, $user), 403);
        abort_unless(array_key_exists($type, self::TYPES), 404);

        $batch->loadMissing(['generatedBy:id,name', 'approvedBy:id,name', 'orgUnit:id,name', 'departmentStream:id,name']);

        $title = self::TYPES[$type];
        $slug = Str::slug($title);
        $existing = $batch->documents()
            ->where('title', $title)
            ->where('status', 'generated')
            ->latest('version')
            ->first();
        $version = ($existing?->version ?? 0) + 1;
        $fileName = "{$slug}-{$batch->batch_number}.pdf";
        $path = "payroll-batch-documents/{$batch->id}/{$slug}-v{$version}.pdf";

        $pdf = $this->pdf->make(
            "{$title} - {$batch->batch_number}",
            $this->linesFor($batch, $title),
        );

        Storage::disk('local')->put($path, $pdf);

        if ($existing && Storage::disk($existing->disk)->exists($existing->file_path)) {
            Storage::disk($existing->disk)->delete($existing->file_path);
        }

        $document = $existing ?? new Document();
        $document->fill([
            'title' => $title,
            'file_name' => $fileName,
            'file_path' => $path,
            'disk' => 'local',
            'mime_type' => 'application/pdf',
            'file_size' => strlen($pdf),
            'version' => $version,
            'status' => 'generated',
            'uploaded_by' => $user?->id,
            'remarks' => 'Generated from payroll batch. Official format pending finalization.',
        ]);
        $document->documentable()->associate($batch);
        $document->save();

        return $document->refresh();
    }

    public function isGeneratedFinalDocument(Document $document): bool
    {
        return $document->documentable_type === (new PayrollBatch())->getMorphClass()
            && $document->status === 'generated'
            && in_array($document->title, self::TYPES, true);
    }

    /**
     * @return array<int, string>
     */
    private function linesFor(PayrollBatch $batch, string $title): array
    {
        return [
            'This generated document is a working system output. The official government format and wording are pending confirmation.',
            '',
            'Document: '.$title,
            'Batch Number: '.$batch->batch_number,
            'Batch Type: '.$batch->typeLabel(),
            'Status: '.$batch->statusLabel(),
            'Period: '.$batch->periodLabel(),
            'Payment Date: '.($batch->payment_date?->format('d M Y') ?? 'Not specified'),
            'Office: '.($batch->orgUnit?->name ?? 'All scoped offices'),
            'Department Stream: '.($batch->departmentStream?->name ?? 'Not specified'),
            '',
            'Generated By: '.($batch->generatedBy?->name ?? 'System'),
            'Generated On: '.now()->format('d M Y, h:i A'),
            'Approved By: '.($batch->approvedBy?->name ?? 'MD / final approver'),
            'Approved On: '.($batch->approved_at?->format('d M Y, h:i A') ?? 'Not recorded'),
            '',
            'Employee Count: '.number_format($batch->items()->count()),
            'Gross Total: '.$this->money((float) $batch->gross_total),
            'Deduction Total: '.$this->money((float) $batch->deduction_total),
            'Net Payable: '.$this->money((float) $batch->net_total),
            'Disbursed Total: '.$this->money((float) $batch->disbursed_total),
            '',
            'Signature / Seal:',
            '',
            'Authorized Signatory: ______________________________',
            'Date: ______________________________',
        ];
    }

    private function money(float $amount): string
    {
        return 'Rs. '.number_format($amount, 2);
    }
}
